### ISSUE TITLE
TypeError: no _dump_data is defined for class OpenSSL::X509::Store

### ISSUE THREAD

**Issue by hickscorp** [godfat/rest-graph#9]
Playing around with `rest-graph`. Simple test yields error:

```
RestGraph.new access_token: token
client.get 'me'

RestGraph: spent 0.307645 Requested https://graph.facebook.com/me?access_token=REMOVED
TypeError: no _dump_data is defined for class OpenSSL::X509::Store
from ~/.rvm/gems/ruby-2.3.1@REMOVED/gems/redis-store-1.1.7/lib/redis/store/marshalling.rb:29:in `dump'
```

**Comment by godfat** [comment]
First I'll suggest you to move to [rest-more](https://github.com/godfat/rest-more)'s [facebook client](https://github.com/godfat/rest-more/blob/master/lib/rest-core/client/facebook.rb) because I am no longer actively working on rest-graph.

And I can't seem to reproduce the problem you have here. Your error was raised from `redis-store` gem, did it do some weird monkey patching break this? Also if you don't have `rest-client` installed, you might want to install it because rest-graph is using it. (or `em-http-request`, that's why it's not strictly set as a dependency)

**Comment by hickscorp** [comment]
@godfat Thanks for the help!

I found how to solve the issue with `rest-graph`: the redis cache isn't compatible with whatever rest-client is doing, it's probably trying to cache non-PORO objects. Giving the `cache: {}` option solved the problem.

I however followed your advice and moved to `rest-more`, which worked better.

Thank you!

**Comment by godfat** [comment]
@hickscorp Awesome! Thanks for moving and letting me know how it went. Let me know if you have any issues with rest-more, by filing an issue or chatting on [gitter](https://gitter.im/godfat/rest-more), or perhaps using the old [google group](https://groups.google.com/forum/#!forum/rest-core) or new [mailing list](http://www.freelists.org/list/rest-core). Personally I am ok with using issues as the discussion threads though, so just pick whatever you like.
